<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Haldiram\'s Sev Bhujia',
                'category_id' => 2,
                'weight' => 0.50,
                'size' => json_encode(['small', 'medium', 'large']),
                'colors' => json_encode(['red', 'green', 'blue']),
                'image' => json_encode(['product-img-1.jpg']),
                'description' => 'A delicious snack made with crispy sev and flavorful spices.',
                'price' => 18.00,
                'sale_price' => 24.00,
                'product_code' => 'HSB001',
                'product_sku' => 'HSB001-SMALL-RED',
                'stock' => '1',
                'slug' => Str::slug('Haldiram\'s Sev Bhujia'),
                'meta_title' => 'Haldiram\'s Sev Bhujia',
                'meta_description' => 'A delicious snack made with crispy sev and flavorful spices.',
            ],
            [
                'name' => 'NutriChoice Digestive',
                'category_id' => 3,
                'weight' => 0.25,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['white', 'brown']),
                'image' => json_encode(['product-img-2.jpg']),
                'description' => 'A healthy digestive biscuit made with wholesome ingredients.',
                'price' => 24.00,
                'sale_price' => null,
                'product_code' => 'NCD001',
                'product_sku' => 'NCD001-SMALL-WHITE',
                'stock' => '1',
                'slug' => Str::slug('NutriChoice Digestive'),
                'meta_title' => 'NutriChoice Digestive',
                'meta_description' => 'A healthy digestive biscuit made with wholesome ingredients.',
            ],
            [
                'name' => 'Cadbury 5 Star Chocolate',
                'category_id' => 3,
                'weight' => 0.30,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['brown', 'gold']),
                'image' => json_encode(['product-img-3.jpg']),
                'description' => 'A rich and creamy chocolate bar with a smooth texture.',
                'price' => 32.00,
                'sale_price' => 35.00,
                'product_code' => 'C5S001',
                'product_sku' => 'C5S001-SMALL-BROWN',
                'stock' => '1',
                'slug' => Str::slug('Cadbury 5 Star Chocolate'),
                'meta_title' => 'Cadbury 5 Star Chocolate',
                'meta_description' => 'A rich and creamy chocolate bar with a smooth texture.',
            ],
            [
                'name' => 'Onion Flavour Potato',
                'category_id' => 2,
                'weight' => 0.20,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['yellow', 'red']),
                'image' => json_encode(['product-img-4.jpg']),
                'description' => 'A crispy potato snack flavored with onion seasoning.',
                'price' => 3.00,
                'sale_price' => 5.00,
                'product_code' => 'OFP001',
                'product_sku' => 'OFP001-SMALL-YELLOW',
                'stock' => '1',
                'slug' => Str::slug('Onion Flavour Potato'),
                'meta_title' => 'Onion Flavour Potato',
                'meta_description' => 'A crispy potato snack flavored with onion seasoning.',
            ],
            [
                'name' => 'Salted Instant Popcorn',
                'category_id' => 4,
                'weight' => 0.15,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['white', 'yellow']),
                'image' => json_encode(['product-img-5.jpg']),
                'description' => 'A convenient and tasty instant popcorn snack.',
                'price' => 13.00,
                'sale_price' => 18.00,
                'product_code' => 'SIP001',
                'product_sku' => 'SIP001-SMALL-WHITE',
                'stock' => '1',
                'slug' => Str::slug('Salted Instant Popcorn'),
                'meta_title' => 'Salted Instant Popcorn',
                'meta_description' => 'A convenient and tasty instant popcorn snack.',
            ],
            [
                'name' => 'Blueberry Greek Yogurt',
                'category_id' => 1,
                'weight' => 0.40,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['blue', 'white']),
                'image' => json_encode(['product-img-6.jpg']),
                'description' => 'A healthy and delicious Greek yogurt with blueberry flavor.',
                'price' => 18.00,
                'sale_price' => 24.00,
                'product_code' => 'BGY001',
                'product_sku' => 'BGY001-SMALL-BLUE',
                'stock' => '1',
                'slug' => Str::slug('Blueberry Greek Yogurt'),
                'meta_title' => 'Blueberry Greek Yogurt',
                'meta_description' => 'A healthy and delicious Greek yogurt with blueberry flavor.',
            ],
            [
                'name' => 'Britannia Cheese Slices',
                'category_id' => 1,
                'weight' => 0.30,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['yellow', 'white']),
                'image' => json_encode(['product-img-7.jpg']),
                'description' => 'A convenient and tasty cheese slice snack.',
                'price' => 24.00,
                'sale_price' => null,
                'product_code' => 'BCS001',
                'product_sku' => 'BCS001-SMALL-YELLOW',
                'stock' => '1',
                'slug' => Str::slug('Britannia Cheese Slices'),
                'meta_title' => 'Britannia Cheese Slices',
                'meta_description' => 'A convenient and tasty cheese slice snack.',
            ],
            [
                'name' => 'Kellogg\'s Original Cereals',
                'category_id' => 4,
                'weight' => 0.50,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['red', 'yellow']),
                'image' => json_encode(['product-img-8.jpg']),
                'description' => 'A classic and healthy breakfast cereal.',
                'price' => 32.00,
                'sale_price' => 35.00,
                'product_code' => 'KOC001',
                'product_sku' => 'KOC001-SMALL-RED',
                'stock' => '1',
                'slug' => Str::slug('Kellogg\'s Original Cereals'),
                'meta_title' => 'Kellogg\'s Original Cereals',
                'meta_description' => 'A classic and healthy breakfast cereal.',
            ],
            [
                'name' => 'Slurrp Millet Chocolate',
                'category_id' => 2,
                'weight' => 0.25,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['brown', 'gold']),
                'image' => json_encode(['product-img-9.jpg']),
                'description' => 'A delicious and healthy millet chocolate snack.',
                'price' => 20.00,
                'sale_price' => 25.00,
                'product_code' => 'SMC001',
                'product_sku' => 'SMC001-SMALL-BROWN',
                'stock' => '1',
                'slug' => str::slug('Slurrp Millet Chocolate'),
                'meta_title' => 'Slurrp Millet Chocolate',
                'meta_description' => 'A delicious and healthy millet chocolate snack.',
            ],
            [
                'name' => 'Tropicana Orange Juice',
                'category_id' => 1,
                'weight' => 1.00,
                'size' => json_encode(['small', 'medium']),
                'colors' => json_encode(['orange', 'yellow']),
                'image' => json_encode(['product-img-10.jpg']),
                'description' => 'A refreshing and healthy orange juice drink.',
                'price' => 30.00,
                'sale_price' => 35.00,
                'product_code' => 'TOJ001',
                'product_sku' => 'TOJ001-SMALL-ORANGE',
                'stock' => '1',
                'slug' => Str::slug('Tropicana Orange Juice'),
                'meta_title' => 'Tropicana Orange Juice',
                'meta_description' => 'A refreshing and healthy orange juice drink.',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
